"""
sim2real/dexmate_curobo.py

CuRobo-based IK + motion planning for Dexmate Vega.

Mirrors the structure of sim/evaluation/curobo_executor.py but targets
the Dexmate URDF instead of Franka, and operates in a shifted world frame
(Table B at +X offset).

Prerequisites
─────────────
1. pip install curobo  (or ensure ~/Project/curobo/src is on PYTHONPATH)
2. Place vega_1.yml in  curobo/content/configs/robot/
   (see generate_dexmate_yml() below for an auto-generator helper)
3. sim2real/assets_dexmate/vega_1.usd  must exist
"""
from __future__ import annotations

import os
import sys
import threading
import time
from pathlib import Path
from typing import Any

import numpy as np
import torch
from scipy.spatial.transform import Rotation
from termcolor import cprint

SIM2REAL_DIR = Path(__file__).resolve().parent
PROJ_DIR = SIM2REAL_DIR.parent
SIM_DIR  = PROJ_DIR / "sim"

for _p in [str(SIM_DIR), str(PROJ_DIR)]:
    if _p not in sys.path:
        sys.path.insert(0, _p)

# CuRobo source path (mirrors curobo_executor.py)
for _c in [
    os.path.expanduser("~/Project/curobo/src"),
    os.path.expanduser("~/curobo/src"),
    "/home/vision/Project/curobo/src",
]:
    if os.path.isdir(os.path.join(_c, "curobo")):
        sys.path.insert(0, _c)
        break

from sim2real.scene_builder import (           # noqa: E402
    TABLE_SCALE, TABLE_TOP_Z,
    DEXMATE_ROBOT_POSITION, DEXMATE_ROBOT_ORIENTATION,
    TABLE_B_POSITION,
)
from sim2real.retarget_utils import normalize  # noqa: E402

_DEXMATE_MG: Any = None   # singleton MotionGen for Dexmate


# ── robot base transform (Table-B frame) ─────────────────────────────────────

def get_dexmate_base_transform() -> tuple[np.ndarray, np.ndarray]:
    yaw = np.deg2rad(DEXMATE_ROBOT_ORIENTATION[2])
    c, s = np.cos(yaw), np.sin(yaw)
    T = np.eye(4)
    T[:3, :3] = np.array([[c, -s, 0], [s, c, 0], [0, 0, 1]])
    T[:3, 3]  = DEXMATE_ROBOT_POSITION
    return T, np.linalg.inv(T)


def world_to_robot_pose_dexmate(
    pos_w: np.ndarray, quat_wxyz_w: np.ndarray
) -> tuple[np.ndarray, np.ndarray]:
    _, T_rw = get_dexmate_base_transform()
    pos_r = (T_rw @ np.append(pos_w, 1.0))[:3]
    R_w  = Rotation.from_quat([quat_wxyz_w[1], quat_wxyz_w[2], quat_wxyz_w[3], quat_wxyz_w[0]])
    R_rw = Rotation.from_matrix(T_rw[:3, :3])
    R_r  = R_rw * R_w
    q    = R_r.as_quat()
    return pos_r, np.array([q[3], q[0], q[1], q[2]])


# ── CuRobo robot config generator ────────────────────────────────────────────

DEXMATE_CUROBO_YML = SIM2REAL_DIR / "config" / "dexmate_vega_1.yml"

DEXMATE_YML_TEMPLATE = """\
# Auto-generated by sim2real/dexmate_curobo.py
robot_cfg:
  kinematics:
    usd_path: "{usd_path}"
    usd_robot_root: "/vega_1"
    isaac_usd_path: ""
    usd_flip_joints: {{}}
    usd_flip_joint_limits: []
    urdf_path: ""
    asset_root_path: ""
    base_link: "base"
    ee_link: "R_ee"
    link_names: null
    lock_joints: {{}}
    extra_links: {{}}
    mesh_link_names: null
    collision_link_names: null
    collision_spheres: "spheres/dexmate_vega_1.yml"
    collision_sphere_buffer: 0.005
    use_global_cumul: true
    self_collision_ignore: {{}}
    self_collision_buffer: {{}}
    load_link_names_with_mesh: false
    cspace:
      joint_names:
        - "R_arm_j1"
        - "R_arm_j2"
        - "R_arm_j3"
        - "R_arm_j4"
        - "R_arm_j5"
        - "R_arm_j6"
        - "R_arm_j7"
      retract_config:
        - -0.84
        - -0.51
        - -0.37
        - -1.30
        - 0.65
        - 0.29
        - 0.03
      null_space_weight: [1, 1, 1, 1, 1, 1, 1]
      cspace_distance_weight: [1, 1, 1, 1, 1, 1, 1]
      max_jerk: 500.0
      max_acceleration: 15.0
"""

DEXMATE_SPHERES_TEMPLATE = """\
# Collision spheres for Dexmate Vega right arm (approximate, right arm only)
# Generated by sim2real/dexmate_curobo.py – tune radii after visual inspection.
R_arm_l1:
  - "0.0 0.0 0.0 0.08"
R_arm_l2:
  - "0.0 0.0 0.0 0.07"
R_arm_l3:
  - "0.0 0.0 0.0 0.07"
R_arm_l4:
  - "0.0 0.0 0.0 0.06"
R_arm_l5:
  - "0.0 0.0 0.0 0.06"
R_arm_l6:
  - "0.0 0.0 0.0 0.05"
R_arm_l7:
  - "0.0 0.0 0.0 0.05"
R_arm_l8:
  - "0.0 0.0 0.05 0.05"
"""


def ensure_dexmate_curobo_config() -> Path:
    """
    Write vega_1.yml + collision spheres into curobo's config tree if missing.
    Returns path to the yml file (for user information).
    """
    import yaml

    # Locate curobo content dir
    content_root: Path | None = None
    for _c in sys.path:
        candidate = Path(_c) / "curobo" / "content" / "configs" / "robot"
        if candidate.is_dir():
            content_root = candidate
            break
    if content_root is None:
        cprint("[dexmate_curobo] Could not find curobo content dir; skipping yml generation.", "yellow")
        return DEXMATE_CUROBO_YML

    yml_dst = content_root / "dexmate_vega_1.yml"
    spheres_dst = content_root.parent / "robot" / "spheres" / "dexmate_vega_1.yml"

    if not yml_dst.exists():
        usd_abs = str((SIM2REAL_DIR / "assets_dexmate" / "vega_1.usd").resolve())
        yml_dst.write_text(DEXMATE_YML_TEMPLATE.format(usd_path=usd_abs))
        cprint(f"[dexmate_curobo] wrote {yml_dst}", "green")

    spheres_dst.parent.mkdir(parents=True, exist_ok=True)
    if not spheres_dst.exists():
        spheres_dst.write_text(DEXMATE_SPHERES_TEMPLATE)
        cprint(f"[dexmate_curobo] wrote {spheres_dst}", "green")

    return yml_dst


# ── world config builder (mirrors curobo_world.py helpers) ───────────────────

def _build_dexmate_world_config(
    table_pos_r: np.ndarray,
    ground_pos_r: np.ndarray,
) -> dict:
    return {
        "cuboid": {
            "table": {
                "dims": list(TABLE_SCALE),
                "pose": [*table_pos_r.tolist(), 1, 0, 0, 0],
            },
            "ground": {
                "dims": [20.0, 20.0, 0.1],
                "pose": [*ground_pos_r.tolist(), 1, 0, 0, 0],
            },
        }
    }


# ── init CuRobo for Dexmate ──────────────────────────────────────────────────

def init_dexmate_curobo() -> Any:
    from curobo.wrap.reacher.motion_gen import MotionGen, MotionGenConfig

    extra = "/home/vision/isaacsim/kit/python/bin:/usr/local/cuda/bin"
    if extra not in os.environ.get("PATH", ""):
        os.environ["PATH"] = extra + ":" + os.environ.get("PATH", "")

    ensure_dexmate_curobo_config()

    _, T_rw = get_dexmate_base_transform()
    table_pos_r  = (T_rw @ np.append(TABLE_B_POSITION, 1.0))[:3]
    ground_pos_r = (T_rw @ np.array([0, 0, -0.005, 1.0]))[:3]
    world_config = _build_dexmate_world_config(table_pos_r, ground_pos_r)

    cprint("   [dexmate-curobo] loading MotionGenConfig...", "yellow")
    t0 = time.time()
    mg_config = MotionGenConfig.load_from_robot_config(
        "dexmate_vega_1.yml", world_config, interpolation_dt=0.02
    )
    cprint(f"   [dexmate-curobo] config loaded in {time.time()-t0:.1f}s", "yellow")

    mg = MotionGen(mg_config)

    # Warmup with heartbeat
    TIMEOUT = int(os.environ.get("CUROBO_WARMUP_TIMEOUT", "600"))
    done  = threading.Event()
    exc_: list[Exception] = []

    def _warmup():
        try:
            mg.warmup()
        except Exception as e:
            exc_.append(e)
        finally:
            done.set()

    def _hb():
        t1 = time.time()
        while not done.is_set():
            done.wait(timeout=10)
            if not done.is_set():
                print(f"   [dexmate-warmup] {int(time.time()-t1)}s...", flush=True)
                if time.time() - t1 > TIMEOUT:
                    os.kill(os.getpid(), 9)

    threading.Thread(target=_warmup, daemon=True).start()
    threading.Thread(target=_hb,      daemon=True).start()
    done.wait()
    if exc_:
        raise RuntimeError(f"Dexmate CuRobo warmup failed: {exc_[0]}") from exc_[0]
    cprint(f"   [dexmate-curobo] ready ✅ ({time.time()-t0:.1f}s)", "green")
    return mg


# ── plan one trajectory ───────────────────────────────────────────────────────

def plan_dexmate_trajectory(
    motion_gen: Any,
    current_joints: np.ndarray,    # (7,) right-arm joints
    target_pos_world: np.ndarray,
    target_quat_wxyz_world: np.ndarray,
    label: str = "",
) -> np.ndarray | None:
    from curobo.types.math import Pose
    from curobo.types.robot import JointState as CuJointState
    from curobo.wrap.reacher.motion_gen import MotionGenPlanConfig

    pos_r, quat_r = world_to_robot_pose_dexmate(target_pos_world, target_quat_wxyz_world)
    start_state = CuJointState.from_position(
        torch.tensor(current_joints, dtype=torch.float32).unsqueeze(0).cuda(),
    )
    goal_pose = Pose.from_list([
        float(pos_r[0]), float(pos_r[1]), float(pos_r[2]),
        float(quat_r[0]), float(quat_r[1]), float(quat_r[2]), float(quat_r[3]),
    ])
    result = motion_gen.plan_single(
        start_state, goal_pose,
        MotionGenPlanConfig(max_attempts=10, enable_graph=True, enable_opt=True),
    )
    ok = result.success.item() if hasattr(result.success, "item") else bool(result.success)
    if ok:
        traj = result.get_interpolated_plan()
        cprint(f"      [{label}] Dexmate plan OK: {traj.position.shape[0]} steps", "green")
        return traj.position.cpu().numpy()
    cprint(f"      [{label}] Dexmate plan FAILED", "red")
    return None
